name: Build and test

# Controls when the action will run. Triggers the workflow on push
on:
  push:
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:

  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows",
            os: windows-2019,
            build_type: "Debug",
            cc: "cl",
            cxx: "cl",
            generators: "Visual Studio 16 2019"
          }
          - {
            name: "Ubuntu",
            os: ubuntu-latest,
            build_type: "Debug",
            cc: "clang",
            cxx: "clang++",
            generators: "Ninja"
          }
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies on windows
        if: matrix.config.os == 'Windows'
        run: |
          choco install ninja cmake
          ninja --version
          cmake --version
          #cmd "${{ matrix.config.environment_script }}"

      - name: Install dependencies on ubuntu
        if: matrix.config.name == 'Ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake
          ninja --version
          cmake --version
          clang --version

      - name: Print env
        run: |
            echo github.event.action: ${{ github.event.action }}
            echo github.event_name: ${{ github.event_name }}

      - name: Configure
        run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D ${{ matrix.config.generators }}

      - name: Build
        run: cmake --build ./build --config ${{env.BUILD_TYPE}}