name: Build and test

# Controls when the action will run. Triggers the workflow on push
on:
  push:
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:

  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows",
            os: windows-latest,
            cc: "cl",
            cxx: "cl",
            generators: "Visual Studio 16 2019"
          }
          - {
            name: "Ubuntu",
            os: ubuntu-latest,
            cc: "gcc-10",
            cxx: "g++-10",
            generators: "Ninja"
          }
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies on windows
        if: matrix.config.name == 'Windows'
        run: |
          choco install ninja cmake
          ninja --version
          cmake --version

      - name: Install dependencies on ubuntu
        if: matrix.config.name == 'Ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake
          sudo apt-get install build-essential libgtk-3-dev
          sudo apt install libglew-dev
          sudo apt-get install curl
          sudo apt-get install libssl-dev libcurl4-openssl-dev
          sudo apt-get install libgl1-mesa-dev xorg-dev
          ninja --version
          cmake --version
          clang --version

      - name: Print env
        run: |
            echo github.event.action: ${{ github.event.action }}
            echo github.event_name: ${{ github.event_name }}

      - name: Configure windows
        if: matrix.config.name == 'Windows'
        run: cmake -B ./build -AWin32 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Configure ubuntu
        if: matrix.config.name == 'Ubuntu'
        run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ./build --config ${{env.BUILD_TYPE}}

      - name: Base Test Windows
        if: matrix.config.name == 'Windows'
        shell: bash
        run: tests/Debug/test_base.exe

      - name: Base Test Linux
        if: matrix.config.name == 'Ubuntu'
        shell: bash
        run: tests/test_base

      - name: Pathfinder Test Windows
        if: matrix.config.name == 'Windows'
        shell: bash
        run: tests/Debug/test_pathfinder.exe

      - name: Pathfinder Test Linux
        if: matrix.config.name == 'Ubuntu'
        shell: bash
        run: tests/test_pathfinder

      - name: StateMachine Test Windows
        if: matrix.config.name == 'Windows'
        shell: bash
        run: tests/Debug/test_stateMachine.exe

      - name: StateMachine Test Linux
        if: matrix.config.name == 'Ubuntu'
        shell: bash
        run: tests/test_stateMachine

      - name: WorldGenerator Test Windows
        if: matrix.config.name == 'Windows'
        shell: bash
        run: tests/Debug/test_generator.exe

      - name: WorldGenerator Test Linux
        if: matrix.config.name == 'Ubuntu'
        shell: bash
        run: tests/test_generator